classifyme/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #/admin/
    url(r'admin/$', views.admin, name='admin'),
    #/classifyme/
    url(r'^classifyme/$', views.home, name='home'),
    #/classifyme/input/
    url(r'^classifyme/input/$', views.input, name='input'),
    #/classifyme/input/data/
    url(r'^classifyme/input/data/$', views.data, name='data'),
    #/classifyme/input/data/1/edit/
    url(r'^classifyme/input/data/(?P<buku_id>\d+)/edit/$', views.edit_data, name='edit_data'),
    #/classifyme/input/data/1/
    url(r'^classifyme/input/data/(?P<buku_id>\d+)/$', views.textmining, name='textmining'),
    #/classifyme/input/data/1/hasil
    url(r'^classifyme/input/data/(?P<buku_id>\d+)/hasil/$', views.hasil, name='hasil'),
]

klasifikasiteks/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('classifyme.urls', namespace='classifyme')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classifyme/models.py
from django.db import models
from .validators import validate_file_extension
import datetime

class TrainingSetPos(models.Model):
    nama = models.CharField(max_length=100, null=True)
    file = models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', validators=[validate_file_extension])

    def __str__(self):
        return self.nama

class TrainingSetNeg(models.Model):
    nama = models.CharField(max_length=100, null=True)
    file = models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', validators=[validate_file_extension])

    def __str__(self):
        return self.nama

class Buku(models.Model):
    tahun_choices = []
    for y in range(1990, (datetime.datetime.now().year+5)):
        tahun_choices.append((y, y))

    penulis = models.CharField(max_length=20)
    judul = models.CharField(max_length=100)
    penerbit = models.CharField(max_length=30)
    tahun_terbit = models.IntegerField(choices=tahun_choices, default=datetime.datetime.now().year)
    training_set_positif = models.ForeignKey(TrainingSetPos, null=True)
    training_set_negatif = models.ForeignKey(TrainingSetNeg, null=True)
    testing_set = models.FileField(null=True, upload_to='files/%Y/%m/%d/', validators=[validate_file_extension])
    priors_pos = models.FloatField(blank=True, null=True)
    priors_neg = models.FloatField(blank=True, null=True)
    hasil_pos = models.FloatField(blank=True, null=True)
    hasil_neg = models.FloatField(blank=True, null=True)
    hasil_klasifikasi = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.judul

classifyme/forms.py
from django import forms
from .models import Buku

class BukuForm(forms.ModelForm):
    class Meta:
        model = Buku
        fields = ('penulis', 'judul', 'penerbit', 'tahun_terbit', 'training_set_positif', 'training_set_negatif', 'testing_set')

classifyme/views.py
import csv
from django.shortcuts import render, get_object_or_404
from .forms import BukuForm
from .models import Buku
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import collections

def admin(request):
    return render(request, admin.site.urls, {})

def home(request):
    return render(request, 'classifyme/home.html', {})

def input(request):
    if request.method == 'POST':
        buku = BukuForm(request.POST, request.FILES)
        if buku.is_valid():
            buku.save()
            return redirect('classifyme:data')
    else:
        form = BukuForm()
    return render(request, 'classifyme/input.html', {'form': form})

def data(request):
    context = {}
    buku_query = Buku.objects.all()
    context['buku'] = buku_query
    return render(request, 'classifyme/data.html', context)

def edit_data(request, buku_id):
    buku = get_object_or_404(Buku, id=buku_id)
    if request.method == 'POST':
        form = BukuForm(request.POST, request.FILES, instance=buku)
        if form.is_valid():
            buku.save()
            return HttpResponseRedirect(reverse('classifyme:data',))
    else:
        form = BukuForm(instance=buku)
    return render(request, 'classifyme/edit.html', {'form': form})

def textmining(request, buku_id):
    buku = get_object_or_404(Buku, id=buku_id)
    context = {}
    selected_buku = Buku.objects.get(id=int(buku_id))
    context['buku'] = selected_buku

    #membuka file training set positif
    training_set_positif = ''
    with open('media/{}'.format(selected_buku.training_set_positif.file)) as csvfile:
        csvreader = csv.DictReader(csvfile, delimiter=';', quotechar='"')
        total_row_positif = 0
        for row in csvreader:
            total_row_positif += 1
            training_set_positif += row['Review']
    context['total_row_positif'] = total_row_positif
    context['training_set_positif'] = training_set_positif

    #textmining
    filtered_word_positif = []
    stop_words = set(stopwords.words("bahasa"))
    word_list = set(stopwords.words("wordlist_pos"))
    case_folding_pos = training_set_positif.lower() #case folding
    tokenized_words_positif = word_tokenize(case_folding_pos) #tokenizing
    for w in tokenized_words_positif:
        if w not in stop_words and w in word_list: #filtering
            filtered_word_positif.append(w)
    context['filtered_word_positif'] = filtered_word_positif

    #count(w, training_pos)
    word_counts = collections.Counter(filtered_word_positif)
    wordfreq_positif_list = []
    for w, cp in sorted(word_counts.items()):
        wordfreq_positif_list.append({'w': w, 'cp': cp})
    #print('WORDFREQ_POSITIF_LIST', wordfreq_positif_list)
    context['wordfreq_positif_list'] = wordfreq_positif_list

    #jumlah kata dalam training set positif
    jumlah_kata_positif = len(filtered_word_positif)
    print('JUMLAH_KATA_POSITIF', jumlah_kata_positif)
    context['jumlah_kata_positif'] = jumlah_kata_positif

    #membuka file training set negatif
    training_set_negatif = ''
    with open('media/{}'.format(selected_buku.training_set_negatif.file)) as csvfile:
        csvreader = csv.DictReader(csvfile, delimiter=';', quotechar='"')
        total_row_negatif = 0
        for row in csvreader:
            total_row_negatif += 1
            training_set_negatif += row['Review']
    context['total_row_negatif'] = total_row_negatif
    context['training_set_negatif'] = training_set_negatif

    #textmining
    filtered_word_negatif = []
    stop_words = set(stopwords.words("bahasa"))
    word_list = set(stopwords.words("wordlist_neg"))
    case_folding_neg = training_set_negatif.lower() #case folding
    tokenized_words_negatif = word_tokenize(case_folding_neg) #tokenizing
    for w in tokenized_words_negatif:
        if w not in stop_words and w in word_list: #filtering
            filtered_word_negatif.append(w)
    context['filtered_word_negatif'] = filtered_word_negatif

    #count(w, training_neg)
    word_counts = collections.Counter(filtered_word_negatif)
    wordfreq_negatif_list = []
    for w, cp in sorted(word_counts.items()):
        wordfreq_negatif_list.append({'w': w, 'cp': cp})
    context['wordfreq_negatif_list'] = wordfreq_negatif_list

    #jumlah kata dalam training set negatif
    jumlah_kata_negatif = len(filtered_word_negatif)
    print('JUMLAH_KATA_NEGATIF', jumlah_kata_negatif)
    context['jumlah_kata_negatif'] = jumlah_kata_negatif

    #total ulasan
    total_ulasan = total_row_positif + total_row_negatif
    context['total_ulasan'] = total_ulasan

    #priors positif
    priors_pos = total_row_positif / total_ulasan
    context['priors_pos'] = priors_pos

    #priors negatif
    priors_neg = total_row_negatif / total_ulasan
    context['priors_neg'] = priors_neg

    #menyimpan hasil priors ke django model field
    selected_priors = Buku.objects.get(id=int(buku_id))
    selected_priors.priors_pos = priors_pos
    selected_priors.priors_neg = priors_neg
    selected_priors.save()

    #kata unik
    unique_words = filtered_word_positif + filtered_word_negatif
    unique_wordfreq_total = nltk.FreqDist(unique_words)
    total_unique_words = unique_wordfreq_total.most_common()
    context['total_unique_words'] = total_unique_words

    #|V| / jumlah kata unik seluruh data percobaan
    unique_wordfreq_total = nltk.FreqDist(unique_words)
    wordfreq_sample_total = 0
    for sample in unique_wordfreq_total:
        wordfreq_sample_total += 1
    print('JUMLAH_KATA_UNIK', wordfreq_sample_total)
    context['wordfreq_sample_total'] = wordfreq_sample_total

    #membuka file testing set
    testing_set = ''
    with open('media/{}'.format(selected_buku.testing_set)) as csvfile:
        csvreader = csv.DictReader(csvfile, delimiter=';', quotechar='"')
        total_row_testing = 0
        for row in csvreader:
            total_row_testing += 1
            testing_set += row['Review']
    print('total_row_testing', total_row_testing)
    context['testing_set'] = testing_set

    #textmining
    filtered_word_testing = []
    stop_words = set(stopwords.words("bahasa"))
    word_list = set(stopwords.words("wordlist"))
    case_folding_test = testing_set.lower() #case folding
    tokenized_words_testing = word_tokenize(case_folding_test) #tokenizing
    for w in tokenized_words_testing:
        if w not in stop_words and w in word_list: #filtering
            filtered_word_testing.append(w)
    print('FILTERED_WORD_TESTING', filtered_word_testing)
    context['filtered_word_testing'] = filtered_word_testing

    #count(w, testing)
    word_counts = collections.Counter(filtered_word_testing)
    wordfreq_testing_list = []
    for w, freq_test in sorted(word_counts.items()):
        if w in filtered_word_testing:
            wordfreq_testing_list.append({'w': w, 'freq_test': freq_test})
    print('WORDFREQ_TESTING_LIST', wordfreq_testing_list)
    context['wordfreq_testing_list'] = wordfreq_testing_list

    #count(w,positif) + 1
    wordfreq_test_in_pos = []
    for item_testing in wordfreq_testing_list:
        for item_positif in wordfreq_positif_list:
            if item_testing['w'] == item_positif['w']:
                cp = (item_positif['cp']+1)
                break
        else:
            cp = 1
        wordfreq_test_in_pos.append({'kata': item_testing['w'], 'cp': cp})
    print('WORDFREQ_TEST_IN_POS', wordfreq_test_in_pos)
    context['wordfreq_test_in_pos'] = wordfreq_test_in_pos

    #conditional probabilities positif
    cp_pos_list = []
    for item in wordfreq_test_in_pos:
        if item['kata'] not in cp_pos_list:
            pembilang = item['cp']
            penyebut = jumlah_kata_positif + wordfreq_sample_total
            hasil = pembilang/penyebut
            cp_pos_list.append({'kata': item['kata'], 'hasil': hasil})
    print('CP_POS_LIST', cp_pos_list)
    context['cp_pos_list'] = cp_pos_list

    #hasil akhir positif
    product_cp_pos = 1
    cp_words_pos = []
    i = 0
    while i < len(cp_pos_list):
        cp_words_pos.append(cp_pos_list[i]['hasil'] ** wordfreq_testing_list[i]['freq_test']) #cp**jumlah_kata
        i += 1
    for x in cp_words_pos:
        product_cp_pos *=x #pengalian semua objek dalam list
    hasil_pos = priors_pos * product_cp_pos #pengalian hasil keseluruhan dengan priors
    print('HASIL_POS', hasil_pos)
    context['hasil_pos'] = hasil_pos

    #count(w,negatif) + 1
    wordfreq_test_in_neg = []
    for item_testing in wordfreq_testing_list:
        for item_negatif in wordfreq_negatif_list:
            if item_testing['w'] == item_negatif['w'] :
                cp = (item_negatif['cp']+1)
                break
        else:
            cp = 1
        wordfreq_test_in_neg.append({'kata': item_testing['w'], 'cp': cp})
    print('WORDFREQ_TEST_IN_NEG', wordfreq_test_in_neg)
    context['wordfreq_test_in_neg'] = wordfreq_test_in_neg

    #conditional probabilities negatif
    cp_neg_list = []
    for item in wordfreq_test_in_neg:
        if item['kata'] not in cp_neg_list:
            pembilang = item['cp']
            penyebut = jumlah_kata_negatif + wordfreq_sample_total
            hasil = pembilang/penyebut
            cp_neg_list.append({'kata': item['kata'], 'hasil': hasil})
    print('CP_NEG_LIST', cp_neg_list)
    context['cp_neg_list'] = cp_neg_list

    #hasil akhir negatif
    product_cp_neg = 1
    cp_words_neg = []
    i = 0
    while i < len(cp_neg_list):
        cp_words_neg.append(cp_neg_list[i]['hasil'] ** wordfreq_testing_list[i]['freq_test']) #cp**jumlah_kata
        i += 1
    for x in cp_words_neg:
        product_cp_neg *=x #pengalian semua objek dalam list
    hasil_neg = priors_neg * product_cp_neg #pengalian hasil keseluruhan dengan priors
    print('HASIL_NEG', hasil_neg)
    context['hasil_neg'] = hasil_neg

    #menyimpan hasil akhir ke django model field

templates/classifyme/base.html
{% load staticfiles %}
<html>

  <head>
    <title>ClassifyMe!</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'classifyme.css' %}">
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand">ClassifyMe!</a>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <div class="footer">
        <p style="margin-left: 30px;">&copy; Classifyme! 2017 Design by Adinda Octadia Putri | All Rights Reserved | Narahubung : adindaoctadia@gmail.com</p>
    </div>
  </body>

</html>

templates/classifyme/data.html
{% extends 'classifyme/base.html' %}
{% block content %}

<div class="content container">
  <div class="row">
    <div class="col-md-12">

      <div class="navbar">
        <a href="{% url 'classifyme:input' %}" button type="button" class="btn btn-primary">Tambah Data</a>
      </div>

          <h4 style="border-bottom: 6px solid grey; background-color: lightgrey; padding: 5px;">Daftar Buku</h4>

          <table class="table">
            <thead>
              <th>Data</th>
              <th>Aksi</th>
            </thead>
          <tbody>
          {% for q in buku %}
          <tr>
            <td><p><a href="{% url 'classifyme:textmining' q.id%}">{{q.judul}}</a></p></td>
            <td><a href="{% url 'classifyme:edit_data' q.id %}" class="save btn btn-warning btn-sm" role="button">Ubah</a></td>
          </tr>
          {% endfor %}
          <br><br><br>

          </tbody>
        </table>

    </div>
  </div>
</div>
{% endblock %}

templates/classifyme/edit.html
{% extends 'classifyme/base.html' %}
{% load bootstrap3 %}
{% block content %}

<div class="content container">
  <div class="row">
    <div class="col-md-12">

      <div class="navbar">
        <a href="{% url 'classifyme:home' %}" button type="button" class="btn btn-primary">Beranda</a>
        <a href="{% url 'classifyme:data' %}" button type="button" class="btn btn-primary">Lihat Data</a>
      </div>

      <h4 style="border-bottom: 6px solid grey; background-color: lightgrey; padding: 5px;">Ubah Data</h4><br>

      <form method="POST" enctype="multipart/form-data" class="buku-form">{% csrf_token %}
        {% bootstrap_form form %}
        <h6 style="font-size: 10px; color: grey;">Unggah file dengan format .csv</h5>
        <button type="submit" class="save btn btn-default" style="margin-left: 500px"><a href="{% url 'classifyme:data' %}">Simpan</a></button>
        <br><br><br>
      </form>

    </div>
  </div>
</div>
{% endblock %}

templates/classifyme/hasil.html
{% extends 'classifyme/base.html' %}
{% block content %}

<div class="content container">
  <div class="row">
    <div class="col-md-12">

      <h4 style="border-bottom: 6px solid grey; background-color: lightgrey; padding: 5px;">Hasil Klasifikasi</h4>
      <br>

      {% if hasil_akhir == "Positif" or hasil_akhir == "Negatif" %}
      <h5 style="text-align: center; font-size: 20px;">Hasil klasifikasi dari "{{ buku.judul }}" adalah <strong>{{ hasil_akhir }}</strong></h5>
      <br>
      <h6 style="text-align: center; color: grey;">Klik tombol Selesai untuk menyimpan hasil klasifikasi dan keluar dari aplikasi.</h5>
      <a href="{% url 'classifyme:input' %}" class="save btn btn-primary" role="button" style="margin-left: 525px;">Selesai</a>
      <br><br><br>
      {% else %}
      <h5 style="text-align: center; font-size: 20px;"><strong>{{ hasil_akhir }}</strong></h5>
      <br>
      <h6 style="text-align: center; color: grey;">Kurangi data <em>testing set</em> pada file Anda kemudian unggah kembali.</h5>
      <a href="{% url 'classifyme:data' %}" class="save btn btn-primary" role="button" style="margin-left: 530px;">Ulangi</a>
      <br><br><br>
      {% endif %}

    </div>
  </div>
</div>
{% endblock %}

templates/classifyme/home.html
{% extends 'classifyme/base.html' %}
{% load static %}
{% block content %}

<div class="content container">
  <div class="row">
    <div class="col-md-12">

      <div style="text-align: center">
        <h2 style="color: grey; font-size: 25px;">Selamat Datang di Classifyme!</h2>
        <br>
      </div>

      <div class="tentang">
        <h4 style="background-color: lightgrey; font-size: 20px; padding: 5px;">Tentang Aplikasi</h4>
        <p id="isi">ClassifyMe! adalah aplikasi yang dibuat khusus untuk mengklasifikasikan resensi buku ke dalam resensi positif dan negatif dengan menggunakan teknik <em>preprocessing</em> pada <em>text mining</em> dan Algoritma <em>Naive Bayes</em>.</p><br>
        <img src="{% static 'picture/adinda.jpg' %}" class="img-circle" width="150" height="150"/><br><br>
        <p id="isi">Aplikasi ini dibuat oleh Adinda Octadia Putri, mahasiswi Universitas Gunadarma Jurusan Sistem Informasi angkatan 2013 sebagai syarat dalam mencapai gelar Sarjana Strata Satu (S1).</p><br><br>
      </div>

      <div class="tentang">
        <h4 style="background-color: lightgrey; font-size: 20px; padding: 5px;">Petunjuk Penggunaan</h4>
        <ol class="cara">
          <li id="isi">Untuk menggunakan aplikasi, klik tombol "Mulai" yang ada pada bagian paling bawah halaman ini.<br></li>
          <li id="isi">Masukkan data buku, pilih <em>training set</em>, dan unggah file <em>testing set</em> berekstensi .csv dengan delimiter titik koma (;).<br></li>
          <li id="isi">Data yang sudah dimasukkan akan tampil. Pilih buku yang akan diproses.<br></li>
          <li id="isi">Klik tombol "Proses" di bagian bawah halaman untuk melakukan proses klasifikasi.<br></li>
          <li id="isi">Setelah hasil klasifikasi ditampilkan, klik tombol "Selesai".<br><br></li>
        </ol>
      </div>

    </div>
  </div>
</div>

    <div class="button">
      <a href="{% url 'classifyme:input' %}" class="btn btn-primary" role="button" style="margin-left: 625px">Mulai</a>
    </div>
    <br><br><br>

{% endblock %}

templates/classifyme/input.html
{% extends 'classifyme/base.html' %}
{% block content %}

<div class="content container">
  <div class="row">
    <div class="col-md-12">

      <div class="navbar">
        <a href="{% url 'classifyme:home' %}" button type="button" class="btn btn-primary">Beranda</a>
        <a href="{% url 'classifyme:data' %}" button type="button" class="btn btn-primary">Lihat Data</a>
        <br>
      </div>

      <h4 style="border-bottom: 6px solid grey; background-color: lightgrey; padding: 5px;">Input Buku</h4><br>

      <form method="POST" enctype="multipart/form-data" class="buku-form">{% csrf_token %}
        {{ form.as_p }}
        <h6 style="font-size: 10px; color: grey;">Unggah file dengan format .csv</h5>
        <button type="submit" class="save btn btn-default" style="margin-left: 500px"><a href="{% url 'classifyme:data' %}">Simpan</a></button>
        <br><br><br>
      </form>

    </div>
  </div>
</div>
{% endblock %}

templates/classifyme/textmining.html
{% extends 'classifyme/base.html' %}
{% block content %}

<div class="content container">
  <div class="row">
    <div class="col-md-12">

      <div class="navbar">
        <a href="{% url 'classifyme:data' %}" button type="button" class="btn btn-primary">Lihat Data</a>
      </div>

      <h5 id="get">Judul Buku : {{ buku.judul }}</h5><br>

      <h4 style="border-bottom: 6px solid grey; background-color: lightgrey; padding: 5px;">Training Set</h4>

      <div class="tentang">
        <h5 style="color: white; background-color: #f0ad4e; padding: 5px;">Training Set Positif : </h5>
        <textarea class="file">{{ training_set_positif }}</textarea><br>
      </div>

      <div class="tentang">
        <h5 style="color: white; background-color: #f0ad4e; padding: 5px;">Training Set Negatif : </h5>
        <textarea class="file">{{ training_set_negatif }}</textarea><br>
      </div>

    </div>
  </div>
</div>


<div class="content container">
  <div class="row">
    <div class="col-md-12">

      <h4 style="border-bottom: 6px solid grey; background-color: lightgrey; padding: 5px;">Testing Set</h4><br>
      <textarea style="width: 100%; height: 300px;">{{ testing_set }}</textarea><br><br>

      <h6 style="text-align: center; color: grey;">Klik tombol Proses untuk melanjutkan proses klasifikasi.</h6>
      <a href="{% url 'classifyme:hasil' buku.id %}" class="btn btn-primary" style="margin-left: 515px;" role="button">Proses</a>
      <br><br><br>
    </div>
  </div>
</div>
{% endblock %}